FROM openjdk:8-jdk-alpine

ENV POSTGRES_HOST=
ENV POSTGRES_PORT=${POSTGRES_PORT:-5432}
ENV POSTGRES_DATABASE=${POSTGRES_DATABASE:-state_patch_sql}
ENV POSTGRES_USERNAME=${POSTGRES_USERNAME:-state_patch_sql}
ENV POSTGRES_PASSWORD=

ENV KAFKA_HOST=
ENV KAFKA_PORT=${KAFKA_PATCH_TOPIC:-9092}
ENV KAFKA_PATCH_TOPIC=${KAFKA_PATCH_TOPIC:-patch}
ENV KAFKA_NOTIFY_TOPIC=${KAFKA_NOTIFY_TOPIC:-notify}

COPY ./build/docker/ /app/

CMD ["/app/run.sh"]
